# Generated by Django 3.2.9 on 2021-12-07 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20211205_1434'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingaddress',
            name='data_added',
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='exp_month',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='exp_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
